import './globals.css'
import {Inter} from "next/font/google"
import Script from 'next/script'
 
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({subsets: ["latin"]})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.className}`}>

      <body>
        {children}
      <Script src="https://kit.fontawesome.com/f1f36ce4f1.js"></Script>
      <Script src="https://sdk.scdn.co/spotify-player.js"></Script>  
      </body>
    </html>
  )
}
